//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class HRIS_SMC_DBEntities : DbContext
{
    public HRIS_SMC_DBEntities()
        : base("name=HRIS_SMC_DBEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<tblVivaSetupInfo> tblVivaSetupInfoes { get; set; }
    public virtual DbSet<tblITMayConcern> tblITMayConcerns { get; set; }
    public virtual DbSet<tblInterviewMarksDetail> tblInterviewMarksDetails { get; set; }
    public virtual DbSet<tblVivaDetailsMark> tblVivaDetailsMarks { get; set; }
    public virtual DbSet<tblInterviewBoardMemberFileUp> tblInterviewBoardMemberFileUps { get; set; }
    public virtual DbSet<tblSeparationITMayConcern> tblSeparationITMayConcerns { get; set; }
    public virtual DbSet<DELtblInterviewBoardMemberFileUp> DELtblInterviewBoardMemberFileUps { get; set; }
    public virtual DbSet<tblCandidateCvUpload> tblCandidateCvUploads { get; set; }
    public virtual DbSet<tblInterViewCandidateSelection> tblInterViewCandidateSelections { get; set; }
    public virtual DbSet<tblMedicalCheckUp> tblMedicalCheckUps { get; set; }
    public virtual DbSet<tblMedicalCheckUpMaster> tblMedicalCheckUpMasters { get; set; }
    public virtual DbSet<DEltblInterviewCandidateInfo> DEltblInterviewCandidateInfoes { get; set; }
    public virtual DbSet<tblCandidateSelecTionStatu> tblCandidateSelecTionStatus { get; set; }
    public virtual DbSet<tblTrainingRecordMaster> tblTrainingRecordMasters { get; set; }
    public virtual DbSet<tblEmployeeApprovalByOpearationDetail> tblEmployeeApprovalByOpearationDetails { get; set; }
    public virtual DbSet<tblSurveyQuestionAnswer> tblSurveyQuestionAnswers { get; set; }
    public virtual DbSet<tblSurveySubmitMaster> tblSurveySubmitMasters { get; set; }
    public virtual DbSet<tblSurveySubmitDetail> tblSurveySubmitDetails { get; set; }
    public virtual DbSet<tblSurveyMaster> tblSurveyMasters { get; set; }
    public virtual DbSet<tblSurveyQuestion> tblSurveyQuestions { get; set; }
    public virtual DbSet<tblSurveyQuestionGroup> tblSurveyQuestionGroups { get; set; }
    public virtual DbSet<tblSurveyDetail> tblSurveyDetails { get; set; }
    public virtual DbSet<tblYearlyHoliday> tblYearlyHolidays { get; set; }
    public virtual DbSet<tblFoodRate> tblFoodRates { get; set; }
    public virtual DbSet<tblLunchAllowDetail> tblLunchAllowDetails { get; set; }
    public virtual DbSet<tblLunchAllowMaster> tblLunchAllowMasters { get; set; }
    public virtual DbSet<tblContractualEmpManage> tblContractualEmpManages { get; set; }
    public virtual DbSet<tblTraingingHeading> tblTraingingHeadings { get; set; }
    public virtual DbSet<tblTrainingTopic> tblTrainingTopics { get; set; }
    public virtual DbSet<tblTrainingSetupTopic> tblTrainingSetupTopics { get; set; }
    public virtual DbSet<tblIncrement> tblIncrements { get; set; }
    public virtual DbSet<tblEmployeePromotionEntry> tblEmployeePromotionEntries { get; set; }
    public virtual DbSet<tblEmployeeJobLeft> tblEmployeeJobLefts { get; set; }
    public virtual DbSet<tblEmpTransferAndRedesignation> tblEmpTransferAndRedesignations { get; set; }
    public virtual DbSet<tblLunchAllowDetailsLog> tblLunchAllowDetailsLogs { get; set; }
    public virtual DbSet<tblunchGuestInternInformation> tblunchGuestInternInformations { get; set; }
    public virtual DbSet<tblLunchTimeSet> tblLunchTimeSets { get; set; }
    public virtual DbSet<tblunchGuestInternInformationMaster> tblunchGuestInternInformationMasters { get; set; }
}
