//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class DELtblInterviewBoardMemberFileUp
{
    public int DELInterviewBoardMemberFileUpId { get; set; }
    public Nullable<int> InterviewBoardMemberFileUpId { get; set; }
    public Nullable<int> CompanyId { get; set; }
    public Nullable<int> JobId { get; set; }
    public string FileUp { get; set; }
}

public partial class DEltblInterviewCandidateInfo
{
    public long DELCandidateID { get; set; }
    public Nullable<long> CandidateID { get; set; }
    public int CompanyId { get; set; }
    public int JobID { get; set; }
    public string CandidateName { get; set; }
    public string Address { get; set; }
    public string PhoneNo { get; set; }
    public string EmailAdress { get; set; }
    public string TotalYearsOfExp { get; set; }
    public string LastOrganization { get; set; }
    public string LastPosition { get; set; }
    public string LastExam { get; set; }
    public string LastMajor { get; set; }
    public string LastPassingYear { get; set; }
    public string LastResultType { get; set; }
    public Nullable<int> LastResultDivision { get; set; }
    public string LastResultCGPA { get; set; }
    public string LastResultOutOf { get; set; }
    public Nullable<int> CvUploadID { get; set; }
    public Nullable<int> PhotoUploadID { get; set; }
    public string CurrentSalary { get; set; }
    public string ExpectedSalary { get; set; }
    public string Remarks { get; set; }
    public string ApprovalStatus { get; set; }
    public string EntryBy { get; set; }
    public Nullable<System.DateTime> EntryDate { get; set; }
    public string Updateby { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
    public string VerifiedBy { get; set; }
    public Nullable<System.DateTime> VerifiedDate { get; set; }
    public string ApproveBy { get; set; }
    public Nullable<System.DateTime> ApproveDate { get; set; }
    public string InternalNote { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public Nullable<System.DateTime> DateOfBirth { get; set; }
    public string Age { get; set; }
}

public partial class tblCandidateCvUpload
{
    public int CvUploadId { get; set; }
    public Nullable<int> CandidateID { get; set; }
    public string Cv_Upload { get; set; }
}

public partial class tblCandidateSelecTionStatu
{
    public int CandidateSelecTionStatusId { get; set; }
    public string Name { get; set; }
}

public partial class tblContractualEmpManage
{
    public int ContractualEmpManageId { get; set; }
    public Nullable<bool> IsExtension { get; set; }
    public Nullable<bool> IsRenew { get; set; }
    public Nullable<bool> IsPermanentToContractual { get; set; }
    public Nullable<bool> IsContractualToPermanent { get; set; }
    public Nullable<bool> IsSalaryIncrement { get; set; }
    public Nullable<bool> IsNoIncrement { get; set; }
    public Nullable<bool> IsFacilityIncluded { get; set; }
    public Nullable<bool> IsNoFacility { get; set; }
    public string Remarks { get; set; }
    public string EntryBy { get; set; }
    public Nullable<System.DateTime> EntryDate { get; set; }
    public string UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
    public Nullable<System.DateTime> ExtensionFromDate { get; set; }
    public Nullable<System.DateTime> ExtensionToDate { get; set; }
    public Nullable<System.DateTime> RenewStartDate { get; set; }
    public Nullable<System.DateTime> RenewToDate { get; set; }
    public Nullable<System.DateTime> PermanentToContractualEffectiveDate { get; set; }
    public Nullable<System.DateTime> ContractualToPermanentDate { get; set; }
    public Nullable<int> CompanyId { get; set; }
    public Nullable<int> EmployeeId { get; set; }
    public string ActionStatus { get; set; }
    public Nullable<bool> IsDelete { get; set; }
    public Nullable<int> DeleteBy { get; set; }
    public Nullable<System.DateTime> DeleteDate { get; set; }
    public Nullable<System.DateTime> EffectiveDate { get; set; }
    public Nullable<int> DivisionId { get; set; }
    public Nullable<int> DivisionWId { get; set; }
    public Nullable<int> DepartmentId { get; set; }
    public Nullable<int> SectionId { get; set; }
    public Nullable<int> SubSectionId { get; set; }
    public string EmployeeCode { get; set; }
    public Nullable<int> DesignationId { get; set; }
    public Nullable<int> EmpTypeId { get; set; }
    public Nullable<int> SalaryLoationId { get; set; }
    public Nullable<int> JobLocationId { get; set; }
    public Nullable<int> SalaryGradeId { get; set; }
    public Nullable<int> SalaryStepId { get; set; }
    public Nullable<System.DateTime> ContractEndDate { get; set; }
    public Nullable<System.DateTime> PermanentToContractualEndDate { get; set; }
    public Nullable<bool> AutoProcess { get; set; }
    public string ActionStatus2 { get; set; }
    public Nullable<bool> IsSelfApp { get; set; }
    public Nullable<int> ContractPreiod { get; set; }
    public Nullable<bool> IsAutoUpdate12 { get; set; }
    public Nullable<int> IsSMCFundedProjectstoSMCContract { get; set; }
    public Nullable<int> IsSMCContracttoSMCFundedProjects { get; set; }
    public Nullable<bool> isToProject { get; set; }
    public Nullable<bool> isReappointment { get; set; }
    public string TypeOfPromotion { get; set; }
    public Nullable<bool> IsRedesignation { get; set; }
    public string FromProject { get; set; }
    public string ToProject { get; set; }
}

public partial class tblEmployeeApprovalByOpearationDetail
{
    public int EmployeeApprovalByOpearationDetailId { get; set; }
    public Nullable<int> MasterId { get; set; }
    public Nullable<int> Operation { get; set; }
    public Nullable<int> CompanyId { get; set; }
    public Nullable<int> EmpInfoId { get; set; }
    public Nullable<int> Serial { get; set; }
    public Nullable<int> Isheadperson { get; set; }
}

public partial class tblEmployeeJobLeft
{
    public int EmployeeJobLeftId { get; set; }
    public Nullable<int> CompanyId { get; set; }
    public Nullable<int> EmployeeId { get; set; }
    public Nullable<int> JobLeftTypeId { get; set; }
    public Nullable<System.DateTime> JobLeftDate { get; set; }
    public string Reason { get; set; }
    public Nullable<int> EntryBy { get; set; }
    public Nullable<System.DateTime> EntryDate { get; set; }
    public Nullable<int> UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
    public Nullable<bool> IsClearanceForm { get; set; }
    public Nullable<bool> IsExitInterview { get; set; }
    public Nullable<System.DateTime> SubmissionDate { get; set; }
    public Nullable<int> DeleteBy { get; set; }
    public Nullable<System.DateTime> DeleteDate { get; set; }
    public Nullable<bool> IsDelete { get; set; }
    public Nullable<bool> IsJobLeft { get; set; }
    public string AutoProcess { get; set; }
    public string ActionStatus { get; set; }
    public string ActionStatus2 { get; set; }
    public Nullable<bool> IsSelfApp { get; set; }
    public Nullable<bool> IsAutoUpdate12 { get; set; }
}

public partial class tblEmployeePromotionEntry
{
    public int EmployeePromotionEntryId { get; set; }
    public Nullable<int> CompanyId { get; set; }
    public Nullable<int> FinancialYearId { get; set; }
    public Nullable<int> PSalGradeId { get; set; }
    public Nullable<int> PStepId { get; set; }
    public Nullable<int> PDesignationId { get; set; }
    public Nullable<int> PRepEmpId { get; set; }
    public Nullable<int> NSalGradeId { get; set; }
    public Nullable<int> NSalaryStepId { get; set; }
    public Nullable<int> NDesignationId { get; set; }
    public Nullable<int> NRepEmpId { get; set; }
    public Nullable<int> NPromoTypeId { get; set; }
    public string Remarks { get; set; }
    public Nullable<System.DateTime> Effectivedate { get; set; }
    public string EntryBy { get; set; }
    public Nullable<System.DateTime> EntryDate { get; set; }
    public string UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
    public Nullable<bool> IsDelete { get; set; }
    public string DeleteBy { get; set; }
    public Nullable<System.DateTime> DeleteDate { get; set; }
    public Nullable<int> DivisionId { get; set; }
    public Nullable<int> DivisionWId { get; set; }
    public Nullable<int> DepartmentId { get; set; }
    public Nullable<int> SectionId { get; set; }
    public Nullable<int> SubSectionId { get; set; }
    public Nullable<int> EmployeeId { get; set; }
    public string EmployeeCode { get; set; }
    public Nullable<int> EmpTypeId { get; set; }
    public Nullable<int> SalaryLoationId { get; set; }
    public Nullable<int> JobLocationId { get; set; }
    public Nullable<bool> IsPromotion { get; set; }
    public string AutoProcess { get; set; }
    public Nullable<bool> IsReappointment { get; set; }
    public Nullable<bool> IsSelfApp { get; set; }
    public string ActionStatus { get; set; }
    public string ActionStatus2 { get; set; }
    public Nullable<bool> IsB_DirectlySupervisor { get; set; }
    public Nullable<bool> IsB_ReportingBody { get; set; }
}

public partial class tblEmpTransferAndRedesignation
{
    public int EmpTransferAndRedesignationId { get; set; }
    public Nullable<int> CompanyId { get; set; }
    public Nullable<int> FinancialYearId { get; set; }
    public Nullable<int> EmployeeId { get; set; }
    public Nullable<int> EmpTypeId { get; set; }
    public Nullable<bool> IsInterCompanyTransfer { get; set; }
    public Nullable<bool> IsOnlyTransfer { get; set; }
    public Nullable<int> NewCompanyId { get; set; }
    public Nullable<int> NewSalaryLocationId { get; set; }
    public Nullable<int> NewJobLocationId { get; set; }
    public Nullable<int> NewDivisionId { get; set; }
    public Nullable<int> NewWingId { get; set; }
    public Nullable<int> NewDepartmentId { get; set; }
    public Nullable<int> NewSectionId { get; set; }
    public Nullable<int> NewSubSectionId { get; set; }
    public Nullable<int> NewEmpReportingBodyId { get; set; }
    public Nullable<int> OldCompanyId { get; set; }
    public Nullable<int> OldSalaryLocationId { get; set; }
    public Nullable<int> OldJobLocationId { get; set; }
    public Nullable<int> OldDivisionId { get; set; }
    public Nullable<int> OldWingId { get; set; }
    public Nullable<int> OldDepartmentId { get; set; }
    public Nullable<int> OldSectionId { get; set; }
    public Nullable<int> OldSubSectionId { get; set; }
    public Nullable<int> OldReportingBodyID { get; set; }
    public Nullable<System.DateTime> EffectiveDate { get; set; }
    public string Remarks { get; set; }
    public string EntryBy { get; set; }
    public Nullable<System.DateTime> EntryDate { get; set; }
    public string UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
    public Nullable<bool> IsDelete { get; set; }
    public string DeleteBy { get; set; }
    public Nullable<System.DateTime> DeleteDate { get; set; }
    public string AutoProcess { get; set; }
    public string EmployeeCode { get; set; }
    public Nullable<bool> IsSelfApp { get; set; }
    public string ActionStatus { get; set; }
    public string ActionStatus2 { get; set; }
    public Nullable<bool> IsReappointment { get; set; }
}

public partial class tblFoodRate
{
    public int FoodRateId { get; set; }
    public Nullable<int> CompanyId { get; set; }
    public Nullable<int> EmployeeType { get; set; }
    public Nullable<System.DateTime> EffectiveDate { get; set; }
    public Nullable<decimal> Rate { get; set; }
    public Nullable<int> EntryBy { get; set; }
    public Nullable<System.DateTime> EntryDate { get; set; }
    public Nullable<int> UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
    public Nullable<bool> IsDelete { get; set; }
    public Nullable<int> DeleteBy { get; set; }
    public Nullable<System.DateTime> DeleteDate { get; set; }
}

public partial class tblIncrement
{
    public int IncrementId { get; set; }
    public Nullable<int> CompanyId { get; set; }
    public Nullable<int> FinancialYearId { get; set; }
    public Nullable<int> DivisionId { get; set; }
    public Nullable<int> DivisionWId { get; set; }
    public Nullable<int> DepartmentId { get; set; }
    public Nullable<int> SectionId { get; set; }
    public Nullable<int> SubSectionId { get; set; }
    public Nullable<int> EmployeeId { get; set; }
    public string EmployeeCode { get; set; }
    public Nullable<int> DesignationId { get; set; }
    public Nullable<int> EmpTypeId { get; set; }
    public Nullable<int> SalaryLoationId { get; set; }
    public Nullable<int> JobLocationId { get; set; }
    public Nullable<int> SalaryGradeId { get; set; }
    public Nullable<int> CurrentStepId { get; set; }
    public Nullable<int> IncrementalStepId { get; set; }
    public Nullable<decimal> FeedSalary { get; set; }
    public Nullable<int> EntryBy { get; set; }
    public Nullable<System.DateTime> EntryDate { get; set; }
    public Nullable<int> UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
    public Nullable<System.DateTime> EffectiveDate { get; set; }
    public Nullable<bool> IsDelete { get; set; }
    public Nullable<int> DeleteBy { get; set; }
    public Nullable<System.DateTime> DeleteDate { get; set; }
    public string AutoProcess { get; set; }
    public Nullable<int> IncrementTypeId { get; set; }
    public string ActionStatus2 { get; set; }
    public Nullable<bool> IsSelfApp { get; set; }
    public string ActionStatus { get; set; }
}

public partial class tblInterviewBoardMemberFileUp
{
    public int InterviewBoardMemberFileUpId { get; set; }
    public Nullable<int> CompanyId { get; set; }
    public Nullable<int> JobId { get; set; }
    public string FileUp { get; set; }
}

public partial class tblInterViewCandidateSelection
{
    public int InterViewCandidateSelectionId { get; set; }
    public Nullable<int> CandidateID { get; set; }
    public Nullable<int> CompanyId { get; set; }
    public Nullable<int> JobID { get; set; }
    public string CandidateStatus { get; set; }
}

public partial class tblInterviewMarksDetail
{
    public int InterviewMarksDetailsId { get; set; }
    public Nullable<int> JobId { get; set; }
    public int BoardDetailsId { get; set; }
    public int CandidateID { get; set; }
    public Nullable<int> VivaId { get; set; }
    public Nullable<decimal> VivaMarks { get; set; }
    public Nullable<decimal> WrittenMarks { get; set; }
    public Nullable<decimal> OtherMarks { get; set; }
    public string Tag { get; set; }
    public Nullable<int> EntryBy { get; set; }
    public Nullable<System.DateTime> EntryDate { get; set; }
    public Nullable<int> UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
    public Nullable<decimal> VivaOutOf { get; set; }
    public Nullable<decimal> OtherOutOf { get; set; }
    public Nullable<decimal> WrittenOutOf { get; set; }
}

public partial class tblITMayConcern
{
    public int ITMayConcernId { get; set; }
    public Nullable<int> EmployeeId { get; set; }
    public string Header { get; set; }
    public string FirstPara { get; set; }
    public string SeceondPara { get; set; }
    public string ThirdPara { get; set; }
    public Nullable<int> ToEmployeeId { get; set; }
    public string EntryBy { get; set; }
    public Nullable<System.DateTime> EntryDate { get; set; }
    public Nullable<int> UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
}

public partial class tblLunchAllowDetail
{
    public int LunchAllowDetailsID { get; set; }
    public Nullable<int> LunchAllowID { get; set; }
    public Nullable<int> CompanyId { get; set; }
    public Nullable<int> RateId { get; set; }
    public Nullable<int> EmployeeId { get; set; }
    public Nullable<decimal> Rate { get; set; }
    public string Status { get; set; }
    public Nullable<System.DateTime> fromDate { get; set; }
    public Nullable<System.DateTime> ToDate { get; set; }
    public Nullable<System.DateTime> InactiveDate { get; set; }
}

public partial class tblLunchAllowDetailsLog
{
    public int LunchAllowDetailsLogID { get; set; }
    public Nullable<int> LunchAllowDetailsID { get; set; }
    public Nullable<int> LunchAllowID { get; set; }
    public Nullable<int> CompanyId { get; set; }
    public Nullable<int> RateId { get; set; }
    public Nullable<int> EmployeeId { get; set; }
    public Nullable<decimal> Rate { get; set; }
    public string Status { get; set; }
    public Nullable<System.DateTime> fromDate { get; set; }
    public Nullable<System.DateTime> ToDate { get; set; }
    public Nullable<System.DateTime> InactiveDate { get; set; }
    public Nullable<int> EntryBy { get; set; }
    public Nullable<System.DateTime> EntryDate { get; set; }
    public Nullable<int> UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
}

public partial class tblLunchAllowMaster
{
    public int LunchAllowID { get; set; }
    public Nullable<int> EntryBy { get; set; }
    public Nullable<System.DateTime> EntryDate { get; set; }
    public Nullable<int> UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
    public Nullable<bool> IsDelete { get; set; }
    public Nullable<int> DeleteBy { get; set; }
    public Nullable<System.DateTime> DeleteDate { get; set; }
}

public partial class tblLunchTimeSet
{
    public int LunchTimeSetId { get; set; }
    public Nullable<System.TimeSpan> LunchTime { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public Nullable<int> UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
}

public partial class tblMedicalCheckUp
{
    public int MedicalCheckUpId { get; set; }
    public Nullable<int> CompanyId { get; set; }
    public Nullable<int> EmpInfoId { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public string Comments { get; set; }
    public string Remarks { get; set; }
    public Nullable<int> EntryBy { get; set; }
    public Nullable<System.DateTime> EntryDate { get; set; }
    public Nullable<int> UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
    public Nullable<int> MasterId { get; set; }
}

public partial class tblMedicalCheckUpMaster
{
    public int MedicalCheckUpMasterId { get; set; }
    public Nullable<int> CompanyId { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public string Comments { get; set; }
    public Nullable<int> EntryBy { get; set; }
    public Nullable<System.DateTime> EntryDate { get; set; }
    public Nullable<int> UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
    public Nullable<bool> IsDelete { get; set; }
    public Nullable<int> DeleteBy { get; set; }
    public Nullable<System.DateTime> DeleteDate { get; set; }
}

public partial class tblSeparationITMayConcern
{
    public int SeparationITMayConcern { get; set; }
    public Nullable<int> JobleftTypeID { get; set; }
    public Nullable<int> EmployeeId { get; set; }
    public string Header { get; set; }
    public string FirstPara { get; set; }
    public string SeceondPara { get; set; }
    public string ThirdPara { get; set; }
    public Nullable<int> ToEmployeeId { get; set; }
    public string EntryBy { get; set; }
    public Nullable<System.DateTime> EntryDate { get; set; }
    public Nullable<int> UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
}

public partial class tblSurveyDetail
{
    public int SurveyDetailsId { get; set; }
    public Nullable<int> SurveyMasterId { get; set; }
    public Nullable<int> SurveyQuestionId { get; set; }
    public Nullable<bool> IsActive { get; set; }
}

public partial class tblSurveyMaster
{
    public int SurveyMasterId { get; set; }
    public string SurveyName { get; set; }
    public Nullable<System.DateTime> SurveyFrom { get; set; }
    public Nullable<System.DateTime> SurveyTo { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public Nullable<int> CompanyId { get; set; }
    public Nullable<int> FinancialYearId { get; set; }
    public Nullable<int> EntryBy { get; set; }
    public Nullable<System.DateTime> EntryDate { get; set; }
    public Nullable<int> UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
    public Nullable<bool> IsDelete { get; set; }
    public Nullable<int> DeleteBy { get; set; }
    public Nullable<System.DateTime> DeleteDate { get; set; }
}

public partial class tblSurveyQuestion
{
    public int SurveyQuestionId { get; set; }
    public string QuestionTitle { get; set; }
    public Nullable<int> SurveyQuestionTypeId { get; set; }
    public Nullable<int> SurveyQuestionGroupId { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public Nullable<int> EntryBy { get; set; }
    public Nullable<System.DateTime> EntryDate { get; set; }
    public Nullable<int> UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
}

public partial class tblSurveyQuestionAnswer
{
    public int SurveyQuestionAnswerId { get; set; }
    public Nullable<int> SurveyQuestionTitleId { get; set; }
    public Nullable<int> SurveyQuestionGroupId { get; set; }
    public string SurveyQuestionAnswer { get; set; }
    public Nullable<int> EntryBy { get; set; }
    public Nullable<System.DateTime> EntryDate { get; set; }
    public Nullable<int> UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
}

public partial class tblSurveyQuestionGroup
{
    public int SurveyQuestionGroupId { get; set; }
    public string SurveyQuestionGroup { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public Nullable<int> EntryBy { get; set; }
    public Nullable<System.DateTime> EntryDate { get; set; }
    public Nullable<int> UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
}

public partial class tblSurveySubmitDetail
{
    public int SurveySubmitDetailId { get; set; }
    public Nullable<int> SurveySubmitMasterId { get; set; }
    public Nullable<int> QuestionGroupId { get; set; }
    public string QuestionGroupName { get; set; }
    public Nullable<int> QuestionNameId { get; set; }
    public string QuestionName { get; set; }
    public Nullable<int> QuestionTypeId { get; set; }
    public string QuestionType { get; set; }
    public Nullable<int> Option01Id { get; set; }
    public string Option01Name { get; set; }
    public Nullable<int> Option02Id { get; set; }
    public string Option02Name { get; set; }
    public Nullable<int> Option03Id { get; set; }
    public string Option03Name { get; set; }
    public Nullable<int> Option04Id { get; set; }
    public string Option04Name { get; set; }
    public Nullable<int> OptionAnsId { get; set; }
    public string OptionAns { get; set; }
    public string Description { get; set; }
}

public partial class tblSurveySubmitMaster
{
    public int SurveySubmitMasterId { get; set; }
    public Nullable<int> EmployeeId { get; set; }
    public string SurveyName { get; set; }
    public Nullable<int> EntryBy { get; set; }
    public Nullable<System.DateTime> EntryDate { get; set; }
    public Nullable<int> UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
    public Nullable<int> SurveyID { get; set; }
}

public partial class tblTraingingHeading
{
    public int TraingingHeadingId { get; set; }
    public string TraingingHeading { get; set; }
    public Nullable<int> TraingingSerial { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public Nullable<int> EntryBy { get; set; }
    public Nullable<System.DateTime> EntryDate { get; set; }
    public Nullable<int> UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
    public Nullable<bool> IsDelete { get; set; }
    public string DeleteBy { get; set; }
    public Nullable<System.DateTime> DeleteDate { get; set; }
}

public partial class tblTrainingRecordMaster
{
    public int TrainingRecordMasterId { get; set; }
    public Nullable<int> CompanyId { get; set; }
    public Nullable<int> FinancialYearId { get; set; }
    public Nullable<int> TrainingTypeId { get; set; }
    public Nullable<int> TrainingBudget2Id { get; set; }
    public string TrainingTitle { get; set; }
    public string TrainingDetails { get; set; }
    public Nullable<int> TrainingOrgId { get; set; }
    public Nullable<int> TrainingOrgLocation { get; set; }
    public Nullable<int> TrainingVenue { get; set; }
    public Nullable<decimal> TrainingCost { get; set; }
    public Nullable<decimal> LogisticCost { get; set; }
    public Nullable<decimal> OtherCost { get; set; }
    public string TrainingDays { get; set; }
    public Nullable<int> NoOfDays { get; set; }
    public Nullable<System.DateTime> StartDate { get; set; }
    public Nullable<System.DateTime> EndDate { get; set; }
    public Nullable<System.TimeSpan> StartTime { get; set; }
    public Nullable<System.TimeSpan> EndTime { get; set; }
    public Nullable<decimal> TotalHoure { get; set; }
    public Nullable<int> EntryBy { get; set; }
    public Nullable<System.DateTime> EntryDate { get; set; }
    public Nullable<int> UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
    public Nullable<bool> IsDelete { get; set; }
    public Nullable<System.DateTime> DeleteDate { get; set; }
    public Nullable<int> DeleteBy { get; set; }
    public string TrainingRecordNo { get; set; }
    public Nullable<decimal> GrandTotal { get; set; }
    public Nullable<decimal> CostPerParticipant { get; set; }
    public string ActionStatus { get; set; }
    public string ApproveBy { get; set; }
    public Nullable<System.DateTime> ApproveDate { get; set; }
    public string ActionStatus2 { get; set; }
}

public partial class tblTrainingSetupTopic
{
    public int TrainingTopicId { get; set; }
    public string TrainingTopic { get; set; }
    public Nullable<int> TraingingSerial { get; set; }
    public Nullable<int> TraingingHeadingId { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public Nullable<int> EntryBy { get; set; }
    public Nullable<System.DateTime> EntryDate { get; set; }
    public Nullable<int> UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
    public Nullable<int> DeleteBy { get; set; }
    public Nullable<System.DateTime> DeleteDate { get; set; }
    public Nullable<bool> IsDelete { get; set; }
}

public partial class tblTrainingTopic
{
    public int TopicId { get; set; }
    public string TrainingTopicTitle { get; set; }
}

public partial class tblunchGuestInternInformation
{
    public int GuestInternInformationId { get; set; }
    public string Type { get; set; }
    public string Name { get; set; }
    public Nullable<int> CompanyId { get; set; }
    public Nullable<int> DivisionId { get; set; }
    public Nullable<int> DepartmentId { get; set; }
    public Nullable<System.DateTime> LunchDate { get; set; }
    public Nullable<int> ReferancePersonId { get; set; }
    public string Remarks { get; set; }
    public Nullable<int> EntryBy { get; set; }
    public Nullable<System.DateTime> EntryDate { get; set; }
    public Nullable<System.DateTime> LunchToDate { get; set; }
    public Nullable<int> UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
    public Nullable<int> MasterId { get; set; }
}

public partial class tblunchGuestInternInformationMaster
{
    public int GuestInternInformationMasterId { get; set; }
    public string Type { get; set; }
    public string Name { get; set; }
    public Nullable<int> CompanyId { get; set; }
    public Nullable<int> DivisionId { get; set; }
    public Nullable<int> DepartmentId { get; set; }
    public Nullable<System.DateTime> LunchDate { get; set; }
    public Nullable<int> ReferancePersonId { get; set; }
    public string Remarks { get; set; }
    public Nullable<int> EntryBy { get; set; }
    public Nullable<System.DateTime> EntryDate { get; set; }
    public Nullable<System.DateTime> LunchToDate { get; set; }
    public Nullable<int> UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
}

public partial class tblVivaDetailsMark
{
    public int VivaDetailsMarkId { get; set; }
    public Nullable<int> JobId { get; set; }
    public int BoardDetailsId { get; set; }
    public int CandidateID { get; set; }
    public Nullable<int> VivaId { get; set; }
    public Nullable<decimal> VivaMarks { get; set; }
    public Nullable<int> EntryBy { get; set; }
    public Nullable<System.DateTime> EntryDate { get; set; }
    public Nullable<int> UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
    public Nullable<decimal> VivaOutOf { get; set; }
}

public partial class tblVivaSetupInfo
{
    public int VivaId { get; set; }
    public string VivaName { get; set; }
    public Nullable<int> CompanyId { get; set; }
    public string Category { get; set; }
    public Nullable<int> EntryBy { get; set; }
    public Nullable<System.DateTime> EntryDate { get; set; }
    public Nullable<int> UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
    public Nullable<bool> IsDelete { get; set; }
    public Nullable<int> DeleteBy { get; set; }
    public Nullable<System.DateTime> DeleteDate { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public string Remarks { get; set; }
}

public partial class tblYearlyHoliday
{
    public int YearlyHolidayId { get; set; }
    public Nullable<int> CompanyId { get; set; }
    public Nullable<System.DateTime> YearlyHolidayFromDate { get; set; }
    public Nullable<System.DateTime> YearlyHolidayToDate { get; set; }
    public string Details { get; set; }
    public Nullable<int> EntryBy { get; set; }
    public Nullable<System.DateTime> EntryDate { get; set; }
    public Nullable<int> UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
    public Nullable<bool> IsDelete { get; set; }
    public Nullable<int> DeleteBy { get; set; }
    public Nullable<System.DateTime> DeleteDate { get; set; }
}
