//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.HRIS_DAO_EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRIS_SMCEntities : DbContext
    {
        public HRIS_SMCEntities()
            : base("name=HRIS_SMCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCompanyInfo> tblCompanyInfoes { get; set; }
        public virtual DbSet<tblDepartment> tblDepartments { get; set; }
        public virtual DbSet<tblDesignationStep> tblDesignationSteps { get; set; }
        public virtual DbSet<tblDesignationType> tblDesignationTypes { get; set; }
        public virtual DbSet<tblDivision> tblDivisions { get; set; }
        public virtual DbSet<tblDivisionWing> tblDivisionWings { get; set; }
        public virtual DbSet<tblCompanyUnit> tblCompanyUnits { get; set; }
        public virtual DbSet<tblMenuTypeSetup> tblMenuTypeSetups { get; set; }
        public virtual DbSet<tblMenuApprovalGroupSetup> tblMenuApprovalGroupSetups { get; set; }
        public virtual DbSet<tblMenuApprovalGroupSetupDetail> tblMenuApprovalGroupSetupDetails { get; set; }
        public virtual DbSet<tblMenuGroupPermission> tblMenuGroupPermissions { get; set; }
        public virtual DbSet<tblMenuGroupPermissionDtl> tblMenuGroupPermissionDtls { get; set; }
        public virtual DbSet<tblMenuApprovalGroupPermission> tblMenuApprovalGroupPermissions { get; set; }
        public virtual DbSet<tblMenuApprovalGroupPermissionDtl> tblMenuApprovalGroupPermissionDtls { get; set; }
        public virtual DbSet<tblEmpCategory> tblEmpCategories { get; set; }
        public virtual DbSet<tblMasterAchievement> tblMasterAchievements { get; set; }
        public virtual DbSet<tblMasterExtraCurriculam> tblMasterExtraCurriculams { get; set; }
        public virtual DbSet<tblMasterHobby> tblMasterHobbies { get; set; }
        public virtual DbSet<tblMasterOtherTalent> tblMasterOtherTalents { get; set; }
        public virtual DbSet<tblAttachmentType> tblAttachmentTypes { get; set; }
        public virtual DbSet<tblEmpAttachment> tblEmpAttachments { get; set; }
        public virtual DbSet<tblEmpAchievement> tblEmpAchievements { get; set; }
        public virtual DbSet<tblEmpExtraCurriculam> tblEmpExtraCurriculams { get; set; }
        public virtual DbSet<tblEmpHobby> tblEmpHobbies { get; set; }
        public virtual DbSet<tblEmpOtherTalent> tblEmpOtherTalents { get; set; }
        public virtual DbSet<tblUserDepartmentPermission> tblUserDepartmentPermissions { get; set; }
        public virtual DbSet<tblMainMenu> tblMainMenus { get; set; }
        public virtual DbSet<tblMenuGroupSetupDetail> tblMenuGroupSetupDetails { get; set; }
        public virtual DbSet<tblApprovalStepInfo> tblApprovalStepInfoes { get; set; }
        public virtual DbSet<tblApprovalStepSetup> tblApprovalStepSetups { get; set; }
        public virtual DbSet<tblApprovalStepSetupStepDtl> tblApprovalStepSetupStepDtls { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblUserCategory> tblUserCategories { get; set; }
        public virtual DbSet<tblUserCompanyMaping> tblUserCompanyMapings { get; set; }
        public virtual DbSet<tblUserType> tblUserTypes { get; set; }
        public virtual DbSet<tblQuarterInfo> tblQuarterInfoes { get; set; }
        public virtual DbSet<tblQuarterMonthInfo> tblQuarterMonthInfoes { get; set; }
        public virtual DbSet<tblDesignation> tblDesignations { get; set; }
        public virtual DbSet<tblInterviewActivity> tblInterviewActivities { get; set; }
        public virtual DbSet<tblInterviewBoardEmpDetail> tblInterviewBoardEmpDetails { get; set; }
        public virtual DbSet<tblInterviewCandidateGrading> tblInterviewCandidateGradings { get; set; }
        public virtual DbSet<tblInterviewCandidateTotalMark> tblInterviewCandidateTotalMarks { get; set; }
        public virtual DbSet<tblInterviewGrading> tblInterviewGradings { get; set; }
        public virtual DbSet<vw_EmpInfo> vw_EmpInfo { get; set; }
        public virtual DbSet<tblEmpContractProject> tblEmpContractProjects { get; set; }
        public virtual DbSet<tblEmpExperience> tblEmpExperiences { get; set; }
        public virtual DbSet<tblEmpChildren> tblEmpChildrens { get; set; }
        public virtual DbSet<tblEmpTraining> tblEmpTrainings { get; set; }
        public virtual DbSet<tblJobCreation> tblJobCreations { get; set; }
        public virtual DbSet<tblInterviewCandidateInfo> tblInterviewCandidateInfoes { get; set; }
        public virtual DbSet<tblInterviewBoardSetupDetail> tblInterviewBoardSetupDetails { get; set; }
        public virtual DbSet<tblInterviewCandidateInvitation> tblInterviewCandidateInvitations { get; set; }
        public virtual DbSet<tblInterviewCandidateAttandance> tblInterviewCandidateAttandances { get; set; }
        public virtual DbSet<tblInterviewBoardSetupMaster> tblInterviewBoardSetupMasters { get; set; }
        public virtual DbSet<tblMPBudgetDetail> tblMPBudgetDetails { get; set; }
        public virtual DbSet<tblMenuGroupSetup> tblMenuGroupSetups { get; set; }
        public virtual DbSet<tblEmpEducation> tblEmpEducations { get; set; }
        public virtual DbSet<tblEmpReference> tblEmpReferences { get; set; }
        public virtual DbSet<tblEmpNominee> tblEmpNominees { get; set; }
        public virtual DbSet<tblInterviewMarksDetail> tblInterviewMarksDetails { get; set; }
        public virtual DbSet<tblEmployeeType> tblEmployeeTypes { get; set; }
        public virtual DbSet<tblMPBudgetMaster> tblMPBudgetMasters { get; set; }
        public virtual DbSet<tblEmpGeneralInfo> tblEmpGeneralInfoes { get; set; }
    }
}
