//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.HRIS_DAO_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpTraining
    {
        public int EmpTrainingId { get; set; }
        public long EmpInfoId { get; set; }
        public string TrainingName { get; set; }
        public Nullable<int> TrainingType { get; set; }
        public string TrainingDescription { get; set; }
        public Nullable<int> TrainingInstitution { get; set; }
        public string TrainingPlace { get; set; }
        public Nullable<int> TrainingCountry { get; set; }
        public string TrainingAchievment { get; set; }
        public Nullable<System.DateTime> TrFromDate { get; set; }
        public Nullable<System.DateTime> TrToDate { get; set; }
        public Nullable<int> TrainingDays { get; set; }
        public string TrRemarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
