//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.HRIS_DAO_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpGeneralInfo
    {
        public long EmpInfoId { get; set; }
        public Nullable<int> ReportingEmpId { get; set; }
        public string EmpMasterCode { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> DivisionWId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<int> SubSectionId { get; set; }
        public Nullable<int> EmpCategoryId { get; set; }
        public Nullable<int> SalaryGradeId { get; set; }
        public Nullable<int> SalaryStepId { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<int> DesignationTypeId { get; set; }
        public Nullable<int> SalaryLoationId { get; set; }
        public Nullable<int> JobLocationId { get; set; }
        public string EmpName { get; set; }
        public string ShortName { get; set; }
        public string Gender { get; set; }
        public string BloodGroup { get; set; }
        public string TinNo { get; set; }
        public string FatherName { get; set; }
        public Nullable<int> FatherOccupation { get; set; }
        public string MotherName { get; set; }
        public Nullable<int> MotherOccupation { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> DateOfJoin { get; set; }
        public string Religion { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<int> EmpTypeId { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> SalaryFromProject { get; set; }
        public Nullable<bool> IsProbationary { get; set; }
        public Nullable<System.DateTime> ProbationEndDate { get; set; }
        public Nullable<System.DateTime> ExtProbationPeriodDate { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public Nullable<System.DateTime> ExtContractDate { get; set; }
        public string Nationality { get; set; }
        public string NationalityID { get; set; }
        public string PassportNo { get; set; }
        public string ExpectedServiceLength { get; set; }
        public Nullable<System.DateTime> DateOfRetirement { get; set; }
        public Nullable<System.DateTime> DateOfConformation { get; set; }
        public string PlaceOfBirth { get; set; }
        public string AddressPresent { get; set; }
        public Nullable<int> PresentDivision { get; set; }
        public Nullable<int> PresentDistrict { get; set; }
        public Nullable<int> PresentThana { get; set; }
        public string PresentTelNo { get; set; }
        public string AddressPermanent { get; set; }
        public Nullable<int> ParmanentDivision { get; set; }
        public Nullable<int> PermanentDistrict { get; set; }
        public Nullable<int> PermanentThana { get; set; }
        public string ParmanentTelNo { get; set; }
        public string PersonalEmail { get; set; }
        public string OfficialEmail { get; set; }
        public string PersonalMobile { get; set; }
        public string OfficialMobile { get; set; }
        public string FaxNo { get; set; }
        public string EmergencyContactPerson { get; set; }
        public string EmergencyContactAddress { get; set; }
        public string EmergencyContactNumber { get; set; }
        public string SpouseName { get; set; }
        public Nullable<System.DateTime> SpouseDateOfBirth { get; set; }
        public Nullable<int> SpouseMaxEducation { get; set; }
        public Nullable<int> SpouseOccupation { get; set; }
        public Nullable<System.DateTime> DateOfMarriage { get; set; }
        public Nullable<System.DateTime> DateOfConfirmation { get; set; }
        public string ConformationStatus { get; set; }
        public string Age { get; set; }
        public string NAge { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ActionStatus { get; set; }
        public string MedicalInformation { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<int> CandidateID { get; set; }
        public string Remarks { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Updateby { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string EmployeeStatus { get; set; }
        public string InactiveReason { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string EmpImage { get; set; }
        public string EmpSign { get; set; }
        public Nullable<int> PayType { get; set; }
        public string SMCOldCode { get; set; }
        public string NationalIdNo { get; set; }
        public Nullable<bool> IsProgramContractual { get; set; }
        public string NomineeImage { get; set; }
        public Nullable<int> ContractPeriod { get; set; }
        public string Floor { get; set; }
        public Nullable<int> ReferenceID { get; set; }
        public Nullable<System.DateTime> ContractStartDate { get; set; }
        public string ImagePath { get; set; }
        public string NewIDChangePolicy_OldID { get; set; }
        public Nullable<bool> IsSMCFundedProjects { get; set; }
        public Nullable<bool> IsCompanyDirector { get; set; }
        public Nullable<int> leaveRecommenderId { get; set; }
        public Nullable<int> LeaveApprovalId { get; set; }
        public Nullable<bool> IsSpTransfer { get; set; }
        public Nullable<System.DateTime> FatherDOB { get; set; }
        public Nullable<System.DateTime> MotherDOB { get; set; }
        public Nullable<bool> RecruitmentTypeNew { get; set; }
        public Nullable<bool> RecruitmentTypeReplacement { get; set; }
    }
}
