//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.HRIS_DAO_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpOtherTalent
    {
        public int EmpOtherTalentsId { get; set; }
        public long EmpInfoId { get; set; }
        public int MasterOtherTalentsId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
