//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.HRIS_DAO_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpChildren
    {
        public int EmpChildrenId { get; set; }
        public long EmpInfoId { get; set; }
        public string ChildrenName { get; set; }
        public string ChildrenGender { get; set; }
        public Nullable<int> ChildrenOccupation { get; set; }
        public Nullable<System.DateTime> ChildrenDOB { get; set; }
        public string ChildrenMaritalStatus { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
