//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.HRIS_DAO_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpEducation
    {
        public long EmpInfoId { get; set; }
        public Nullable<int> EducationNameId { get; set; }
        public Nullable<int> SubjectGroupId { get; set; }
        public Nullable<int> BoardUniversityId { get; set; }
        public string Result { get; set; }
        public Nullable<int> EducationalInstituteId { get; set; }
        public string PassingYear { get; set; }
        public string CgpaOrTotalMarks { get; set; }
        public Nullable<int> FieldOfSpecializationId { get; set; }
        public Nullable<bool> EduIsLastLevel { get; set; }
        public Nullable<bool> IsProfessionalEdu { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int EmpEducationId { get; set; }
    }
}
