//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.HRIS_DAO_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpExperience
    {
        public int EmpExperienceId { get; set; }
        public long EmpInfoId { get; set; }
        public string ExpCompany { get; set; }
        public string ExpContactPerson { get; set; }
        public string ExpAddress { get; set; }
        public string ExpNatureofBusiness { get; set; }
        public string ExpJobType { get; set; }
        public Nullable<decimal> ExpLeavingSalary { get; set; }
        public Nullable<System.DateTime> ExpFromDate { get; set; }
        public Nullable<System.DateTime> ExpToDate { get; set; }
        public Nullable<bool> ExpLastJob { get; set; }
        public string ExpDesignation { get; set; }
        public string ExpJobDescription { get; set; }
        public string ExpTelNo { get; set; }
        public string ExpRemarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
