//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.HRIS_DAO_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpNominee
    {
        public Nullable<long> EmpInfoId { get; set; }
        public Nullable<int> NominationPurpose { get; set; }
        public string NomineeName { get; set; }
        public Nullable<int> NomineeOccupation { get; set; }
        public Nullable<System.DateTime> DateOfNomination { get; set; }
        public Nullable<decimal> NominationPercentage { get; set; }
        public Nullable<System.DateTime> NomineeDOB { get; set; }
        public Nullable<int> NomineeRelation { get; set; }
        public string NomineeAddress { get; set; }
        public string NomineeTelephone { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int EmpNomineeId { get; set; }
        public string NomNomineImg { get; set; }
    }
}
