//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.HRIS_DAO_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpReference
    {
        public Nullable<long> EmpInfoId { get; set; }
        public string ReferenceName { get; set; }
        public Nullable<int> RefOccupation { get; set; }
        public string RefAddress { get; set; }
        public string RefMobile { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int EmpReferenceId { get; set; }
    }
}
