//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.HRIS_DAO_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInterviewCandidateGrading
    {
        public int InterviewCandidateGradingId { get; set; }
        public int JobID { get; set; }
        public Nullable<int> CandidateID { get; set; }
        public Nullable<decimal> Attitude { get; set; }
        public Nullable<decimal> Language { get; set; }
        public Nullable<decimal> TechnicalSkill { get; set; }
        public Nullable<decimal> IQ { get; set; }
        public Nullable<decimal> GeneralKnowledge { get; set; }
        public Nullable<decimal> Others { get; set; }
        public Nullable<decimal> TimeSence { get; set; }
        public Nullable<decimal> TotalMarks { get; set; }
        public string Grade { get; set; }
        public Nullable<bool> IsRecommended { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Remarks { get; set; }
    }
}
