//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.HRIS_DAO_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInterviewBoardSetupMaster
    {
        public int SetupMasterId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> JobTitleId { get; set; }
        public Nullable<int> InterviewPhase { get; set; }
        public string Vanue { get; set; }
        public Nullable<System.DateTime> InterviewDate { get; set; }
        public string InterviewFromTime { get; set; }
        public string InterviewToTime { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string ApprovalStatus { get; set; }
        public string ApproveBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Remarks { get; set; }
        public string EmailBody { get; set; }
        public Nullable<bool> HasAttachment { get; set; }
        public string AttFileName { get; set; }
    }
}
