//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.HRIS_DAO_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInterviewCandidateAttandance
    {
        public int InterviewCandidateAttandanceId { get; set; }
        public int JobID { get; set; }
        public int CandidateID { get; set; }
        public Nullable<System.TimeSpan> ReportingTime { get; set; }
        public Nullable<System.DateTime> InterviewDate { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string ApprovalStatus { get; set; }
        public string ApproveBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> InterviewPhase { get; set; }
        public string Remarks { get; set; }
    }
}
