//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.HRIS_DAO_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInterviewBoardSetupDetail
    {
        public int BoardDetailsId { get; set; }
        public Nullable<int> MasterId { get; set; }
        public string MemberType { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string Department { get; set; }
        public string Company { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> Written { get; set; }
        public Nullable<bool> Viva { get; set; }
        public Nullable<bool> Other { get; set; }
        public string OtherRemarks { get; set; }
    }
}
