//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.HRIS_DAO_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInterviewCandidateInfo
    {
        public long CandidateID { get; set; }
        public int CompanyId { get; set; }
        public int JobID { get; set; }
        public string CandidateName { get; set; }
        public string Address { get; set; }
        public string PhoneNo { get; set; }
        public string EmailAdress { get; set; }
        public string TotalYearsOfExp { get; set; }
        public string LastOrganization { get; set; }
        public string LastPosition { get; set; }
        public string LastExam { get; set; }
        public string LastMajor { get; set; }
        public string LastPassingYear { get; set; }
        public string LastResultType { get; set; }
        public Nullable<int> LastResultDivision { get; set; }
        public string LastResultCGPA { get; set; }
        public string LastResultOutOf { get; set; }
        public Nullable<int> CvUploadID { get; set; }
        public Nullable<int> PhotoUploadID { get; set; }
        public string CurrentSalary { get; set; }
        public string ExpectedSalary { get; set; }
        public string Remarks { get; set; }
        public string ApprovalStatus { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Updateby { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string VerifiedBy { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
        public string ApproveBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string InternalNote { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Age { get; set; }
        public string Cv_File { get; set; }
        public string Cv_FileName { get; set; }
    }
}
