//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.HRIS_DAO_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInterviewCandidateTotalMark
    {
        public int InterviewCandidateTotalMarksId { get; set; }
        public Nullable<int> CandidateID { get; set; }
        public Nullable<int> InterviewPhase { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<decimal> WrittenMarks { get; set; }
        public Nullable<decimal> WrittenMarksOutOf { get; set; }
        public Nullable<decimal> VivaMarks { get; set; }
        public Nullable<decimal> VivaMarksOutOf { get; set; }
        public Nullable<decimal> OtherMarks { get; set; }
        public Nullable<decimal> OtherMarksOutOf { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
