//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.HRIS_DAO_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInterviewMarksDetail
    {
        public int InterviewMarksDetailsId { get; set; }
        public Nullable<int> JobId { get; set; }
        public int BoardDetailsId { get; set; }
        public int CandidateID { get; set; }
        public Nullable<int> VivaId { get; set; }
        public Nullable<decimal> VivaMarks { get; set; }
        public Nullable<decimal> WrittenMarks { get; set; }
        public Nullable<decimal> OtherMarks { get; set; }
        public string Tag { get; set; }
        public Nullable<int> EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<decimal> VivaOutOf { get; set; }
        public Nullable<decimal> OtherOutOf { get; set; }
        public Nullable<decimal> WrittenOutOf { get; set; }
    }
}
