//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.HRIS_DAO_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJobCreation
    {
        public long JobID { get; set; }
        public string JobCode { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public string Position { get; set; }
        public string Vacancy { get; set; }
        public string JobContext { get; set; }
        public string JobResponsibilities { get; set; }
        public Nullable<bool> PermanenteEmp { get; set; }
        public Nullable<bool> ContractualEmp { get; set; }
        public Nullable<bool> TraineeEmp { get; set; }
        public Nullable<bool> CasualEmp { get; set; }
        public string ExperienceRequirements { get; set; }
        public string AdditionalRequirements { get; set; }
        public string Salary { get; set; }
        public string CompensationandOtherBenefits { get; set; }
        public Nullable<bool> NewspaperDS { get; set; }
        public Nullable<bool> TVDS { get; set; }
        public Nullable<bool> OtherDS { get; set; }
        public string Other { get; set; }
        public Nullable<System.DateTime> CirculationStartDate { get; set; }
        public Nullable<System.DateTime> CirculationsdeadlineDate { get; set; }
        public Nullable<System.DateTime> ProbableInterviewDate { get; set; }
        public Nullable<System.DateTime> ProbableIRecruitmentDate { get; set; }
        public string Remarks { get; set; }
        public string ApprovalStatus { get; set; }
        public string Progress { get; set; }
        public Nullable<int> EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> Updateby { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string VerifiedBy { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
        public string ApproveBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string InternalNote { get; set; }
        public Nullable<bool> IsSalary { get; set; }
        public Nullable<int> ReqCodeId { get; set; }
        public string ActionStatus { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
