//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.HRIS_DAO_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMainMenu
    {
        public int MainMenuId { get; set; }
        public Nullable<int> SL { get; set; }
        public string MenuName { get; set; }
        public string URL { get; set; }
        public string ParantId { get; set; }
        public Nullable<bool> IsApprovalPage { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<int> MenuTypeId { get; set; }
        public string icon { get; set; }
        public Nullable<bool> Add { get; set; }
        public Nullable<bool> View { get; set; }
        public Nullable<bool> Edit { get; set; }
        public Nullable<bool> Delete { get; set; }
        public Nullable<bool> Everyone { get; set; }
        public Nullable<bool> Own { get; set; }
        public Nullable<bool> IsInMainMenu { get; set; }
        public Nullable<bool> IsSupervisor { get; set; }
    }
}
