//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.HRIS_DAO_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMenuGroupSetupDetail
    {
        public int MenuGroupSetupDetailId { get; set; }
        public int MenuGroupSetupId { get; set; }
        public int MainMenuId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> Add { get; set; }
        public Nullable<bool> View { get; set; }
        public Nullable<bool> Edit { get; set; }
        public Nullable<bool> Delete { get; set; }
    }
}
