//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.HRIS_DAO_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMPBudgetDetail
    {
        public int MPBudgetDetailsId { get; set; }
        public Nullable<int> MPBudgetMasterId { get; set; }
        public string Designation { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<int> EmpCategoryId { get; set; }
        public Nullable<int> EmployeeRequisition { get; set; }
        public Nullable<decimal> ReqApproxSalary { get; set; }
        public Nullable<decimal> ReqTotalSalary { get; set; }
        public Nullable<int> QuarterId { get; set; }
        public Nullable<int> SalaryGradeId { get; set; }
        public Nullable<int> SalaryStepId { get; set; }
        public string DtlRemarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string FilterType { get; set; }
        public Nullable<int> EmployeeTypeId { get; set; }
        public Nullable<int> ProjectId { get; set; }
    }
}
