//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.HRIS_DAO_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_EmpInfo
    {
        public long EmpInfoId { get; set; }
        public string EmpMasterCode { get; set; }
        public string EmpName { get; set; }
        public string ShortName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string Religion { get; set; }
        public string Nationality { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string BloodGroup { get; set; }
        public string Gender { get; set; }
        public string AddressPresent { get; set; }
        public string AddressPermanent { get; set; }
        public string MaritalStatus { get; set; }
        public string EmployeeStatus { get; set; }
        public string PayType { get; set; }
        public string CompanyName { get; set; }
        public string DepartmentName { get; set; }
        public string Designation { get; set; }
        public string DivisionName { get; set; }
        public string DivisionWingName { get; set; }
        public string EmpCategoryName { get; set; }
        public string OfficialEmail { get; set; }
        public string OfficialMobile { get; set; }
    }
}
